### ISSUE TITLE
Compose box fails to clear in threaded mode

### ISSUE THREAD

**Issue by starfall-system** [glitch-soc/mastodon#1414]
Per title; writing a toot with "threaded mode" turned on posts the toot but displays the "Oops! An unexpected error occurred" popup and does not clear the compose box. Console output follows. Potentially introduced by 30632ad? Not at all sure, digging through stack traces in front end frameworks is not our forte.

```
TypeError: t.get is not a function
    xe timelines.js:107
    Immutable 4
    xe timelines.js:101
    withMutations Immutable
    xe home-3e50c975a243e704ae27.chunk.js:2
    compose relationships.js:51
    default SwipeableViews.js:637
    default SwipeableViews.js:632
    withMutations Immutable
    default SwipeableViews.js:629
    g Redux
    yt lists.js:27
    yt custom_emojis.js:11
    yt height_cache.js:7
    Redux 2
    ke compose.js:180
    promise callback*ke/< compose.js:172
    r Redux
    onSubmit mouse.js:151
    t options.js:237
    t dropdown.js:207
    t home-3e50c975a243e704ae27.chunk.js:2
    React 12
    unstable_runWithPriority scheduler.production.min.js:296
    React 13
    unstable_runWithPriority scheduler.production.min.js:296
    React 6
    t home-3e50c975a243e704ae27.chunk.js:2
    promise callback*t/< CancelToken.js:50
    componentWillMount height_cache.js:1
    React 12
    default index.js:381
    r ready.js:2
    default index.js:379
    <anonymous> status.js:474
    promise callback* status.js:474
    Webpack 4
alerts.js:60:12
    l alerts.js:60
    yt custom_emojis.js:10
    yt height_cache.js:7
    Redux 2
    ke compose.js:208
    (Async: promise callback)
    ke compose.js:207
    r Redux
    onSubmit mouse.js:151
    t options.js:237
    t dropdown.js:207
    t home-3e50c975a243e704ae27.chunk.js:2
    React 12
    unstable_runWithPriority scheduler.production.min.js:296
    React 13
    unstable_runWithPriority scheduler.production.min.js:296
    React 6
    t home-3e50c975a243e704ae27.chunk.js:2
    (Async: promise callback)
    t CancelToken.js:50
    componentWillMount height_cache.js:1
    React 12
    default index.js:381
    (Async: EventListener.handleEvent)
    r ready.js:2
    default index.js:379
    <anonymous> status.js:474
    (Async: promise callback)
    <anonymous> status.js:474
    Webpack 4
```
