### ISSUE TITLE
Glitch-flavored mobile view does not load for me

### ISSUE THREAD

**Issue by catscode** [glitch-soc/mastodon#662]
I get nothing on my phone anymore using the glitch flavor as of a few days ago. Just a grey screen. This is on iphone SE, with an older version of iOS, across several browsers.

Vanilla flavor displays just fine, though.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
I'm unable to reproduce it from Firefox's “Responsive Design Mode” and I own no iPhone.
Can you access the javascript console and see if there is any reported error?

**Comment by rhaamo** [comment]
working on iOS 12 (beta) on a SE and iOS 11.4.1 on iPad.

@catscode which iOS version are you using ?

**Comment by catscode** [comment]
@rhaamo logged in, on login with glitch flavour i get a grey screen, nothing interactive. but when i use my laptop to switch to vanilla theme, my phone can load that one just fine.

**Comment by rhaamo** [comment]
@catscode ok thanks, great if you can get a trace from tethering.

I might look if 9.x is available on the simulator to get a try.

**Comment by ThibG** [comment]
@catscode hm, the commit you're pointing out doesn't actually change anything to the glitch-soc flavour, so I'm a bit confused

**Comment by rhaamo** [comment]
OK so I spawned a simulator with an iPhone SE on iOS 9.3, here is the error I got in the console :

```
[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (https://oldbytes.space/packs/flavours/glitch/utils.js.map)
[Error] TypeError: Object.values is not a function. (In 'Object.values(action.state.get('accounts').toJS())', 'Object.values' is undefined) ? home-37cc9c25ed677940bac0.js:44932
	(fonction anonyme) (home-37cc9c25ed677940bac0.js:55879)
	promiseReactionJob
```

**Comment by catscode** [comment]
@rhaamo 
oh my gosh it works now! thank you so much! 

i will try to be better about followup in future though, it was unhelpful of me to not do that digging myself.
